### ISSUE TITLE
(WIN64) [FF Quantum x64] {b7a9da5}  'Download all links with uGet' crash

### ISSUE THREAD

**Issue by Baddest-Juju** [ugetdm/uget-extension#3]
Running the latest commit of this git as an unsigned extension scucessfully. When uGet is not already open, using this command seems to cause a crash if uGet was not already open when this is launched.

Interestingly, you see the program start to function properly, listing all the links on the page, but then the program just vanishes. It might not actually be a crash and for some reason it's receiving the instruction to close?

Here's a site that will cause it: https://desktop.telegram.org/

If I open the program before doing this, it works fine. This does not occur when downloading a singular file.

**Comment by slgobinath** [comment]
Fixed with https://github.com/ugetdm/uget-integrator/commit/6fc6baacde71cb39ee98162ac0eed1635a230202.
Please replace the `uget-integrator.py` by https://github.com/ugetdm/uget-integrator/blob/master/bin/uget-integrator (You may need to set the uGet path again)
