### ISSUE TITLE
Opera browser extension out of date

### ISSUE THREAD

**Issue by aneesahmed777** [ugetdm/uget-extension#5]
Hi,
I like the new infrastructure uGet has adopted (with uget-integrator and uget-extension).

**While Chromium and Firefox have go the new uget-extensions, Opera has NOT**.

If you click the link in your [README](https://github.com/ugetdm/uget-extension/blob/master/README.md), you land at the [old Opera extension](https://addons.opera.com/en/extensions/details/uget-integration) page. If you try to install it, this happens:
![screenshot from 2018-04-01 16-49-45](https://user-images.githubusercontent.com/20044850/38172664-340ad350-35ce-11e8-8fbe-e923c398dca4.png)

The Opera addon needs to be updated for the new infrastructure.

**Comment by slgobinath** [comment]
Hi,
I have submitted Opera ad-on with others but Opera developers take more time to verify and publish the add-on. I have sent another reminder to them in case if they missed my add-on submission. Have to wait and see... :(

The issue is already reported at: https://github.com/ugetdm/uget-integrator/issues/14

**Comment by aneesahmed777** [comment]
Would you please share the extension file for manual installation until it appears in Opera Store?

**Comment by slgobinath** [comment]
Please download the `uget-integration-chrome.zip` from [releases](https://github.com/ugetdm/uget-extension/releases) and drag and drop in Opera extensions.

**Comment by slgobinath** [comment]
You can also try this solution https://github.com/ugetdm/uget-integrator/issues/19
